### ISSUE TITLE
Not working with anything but subjects?

### ISSUE THREAD

**Issue by kaosat-dev** [ahomu/rx.observable.combinetemplate#1]
Hello , very nice project, was hoping to find this for rxjs :)
However I am running into issues : 
I am only able to get it working with subjects (as in the provided example) 
but no other combining with any rxjs observables (which work fine otherwise) seems to work:
for example this will not fire 

```
combineTemplate({
      foo:Rx.Observable.just("foo"),
      bar:42
    }).subscribe(value => console.log("got some new value",value) )
```

and  neither does this : 

```
var timer = Rx.Observable.timer(200, 100).timeInterval()
combineTemplate({
      foo:Rx.Observable.just("foo"),
      time:timer
    }).subscribe(value => console.log("got some new value",value) )
```

is there anything I am missing , or did I stumble upon a bug ?

**Comment by ahomu** [comment]
It's bug. :'(
`v0.2.5` fixed it. Give it a try.

**Comment by kaosat-dev** [comment]
It works great!  Thanks for the quick fix too !
